### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-fat4e#3]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by YashasviChaurasia** [comment]
On it.

**Comment by YashasviChaurasia** [comment]
<img width="1440" alt="Screenshot 2022-08-02 at 12 05 25 AM" src="https://user-images.githubusercontent.com/46622381/182220308-9c46d3c6-86a4-41ac-91c1-28a4c9b0bcdf.png">

**Comment by YashasviChaurasia** [comment]
@vanessa-cooper

**Comment by YashasviChaurasia** [comment]
merged
